(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Author of this file: Roman Scoccimarro, rs123@nyu.edu *)


Unprotect[soi,I1,I1q,I2,I22,I2q,I3,the,inti,saint,dist];


Attributes[dot]={Orderless};
dot[x_?AtomQ,x_?AtomQ]:= x^2
dot[-x_,y_]:= -dot[x,y];
dot[-x_-z_,y_]:= -dot[x+z,y];
dot[0,x_]:=0;
dot[x_, al_ y_]:= al dot[x,y] /; NumberQ[N[al]]



Off[RuleDelayed::rhs]



dist=dot[x_,y_+z_]:>dot[x,y]+dot[x,z];



saint[argument_]:= Expand[soi[Expand[ argument //.dist]]] 


terms=40;
whole[q_]:= Floor[Length[q]/terms];


distr[argument_]:= Module[{h,ex,int},
			h=Floor[Length[argument]/50];
			If[h==0, Expand[argument //. dist],
			Do[ex[m]=Expand[ Take[ argument, {1+50 m, 
					50 (m+1)}] //.dist ];
				Share[];
			,{m,0,h-1}];
			ex[h]=Expand[Take[argument,{50 h+1, 
			Length[argument]}] //.dist];
			int=Expand[Sum[ex[m],{m,0,h}]];
			Clear[ex];
			Share[];
			int]
			]
			


soi[x_ + y_]:= soi[x] + soi[y]

soi[- x_]:=- soi[x]

soi[x_]:= x  /; NumberQ[N[x]]

soi[al_ w_]:= al soi[w] /; (FreeQ[al,dot[_,_]] || 
FreeQ[1/ al,dot[_,_]])
 
soi[w_]:= w soi[1] /; (FreeQ[w,dot[_,_]]) 


Unprotect[Power,Abs];
Abs[x_ - y_]^a_ := If[EvenQ[a],(x-y)^a,Abs[x-y] (x-y)^(a-1)] 
Protect[Power,Abs];


(*Unprotect[Times];
z_ /(-x_^2 - y_^2 - 2 dot[x_,y_]) := -z/(x^2 +y^2 + 2 dot[x,y])
Protect[Times];*)


saint[argument_,q_]:= Expand[soi[Expand[argument //.dist],q]] 


soi[x_ + y_,q_]:= soi[x,q] + soi[y,q]

soi[- x_,q_]:=- soi[x,q]

soi[x_,q_]:= 4*Pi x  /; NumberQ[N[x]]

soi[al_ w_,q_]:= al soi[w,q] /; (FreeQ[al,q] || 
FreeQ[1/ al,q])
 
soi[w_,q_]:= w soi[1,q] /; (FreeQ[w,q]) 

soi[ q^r_. w_. ,q]:= q^r soi[ w , q]


I1[a_,b_,c_,x_,y_,z_]:= 
Module[{i,r,k}, If[ TrueQ[EvenQ[a+
b] && EvenQ[b+c]],
 x^(c+a) y^(a+b) z^(b+c) Sum[ Binomial[b,2i] Binomial[i,
r] Binomial[i,k] (2i-1)!! (-1)^(r+k) / ((2i)!!(a+b-2r+1)(b+c-2k+1)),
{i,0,Floor[b/2]},{r,0,i},{k,0,i}],0] ]


I1[a_,b_,c_,d_,e_,f_,x_,y_,z_,w_]:= 
Module[{n,m,k,l,r,s,t}, 
If[ TrueQ[EvenQ[a+b+e] && EvenQ[b+c+f] && EvenQ[d+e+f]],
1/Pi^2 x^(c+a+d) y^(a+b+e) z^(b+c+f) w^(d+e+f) Sum[ 
Binomial[b,2n-k] Binomial[e,2m-k] Binomial[f,k] Binomial[k,
2l] Binomial[n+m-k,r] Binomial[n,s] Binomial[m,t] (-1)^(k+r+
s+t) Beta[n-l+1/2,l+1/2] Beta[m-l+1/2,l+1/2]/ ((a+b+e-2r+1)(b+
c+f-2s+1)(d+e+f-2t+1)),
{n,0,Floor[(b+f)/2]},{m,0,Floor[(e+f)/2]},{k,Max[0,2n-b,2m-e],
Min[f,2n,2m]},{l,0,Floor[k/2]},{r,0,n+m-k},{s,0,n},{t,0,m}] ,0] ]


I1q[a_,b_,x_,y_,q_]:= 
Module[{i,r,k}, If[ TrueQ[EvenQ[a+b]] ,
4 Pi x^(a) y^(b) q^(b+a) Sum[ Binomial[b,2k] Binomial[k,i] (2k-1)!! (-1)^(i)  (1-(dot[x,y]/(x y))^2)^k (dot[x,y]/(x y))^(b-2k)/(
(2k)!! (a+b+2i-2k+1)),{k,0,Floor[b/2]},{i,0,k}],0] ]


soi[dot[x_,y_]^(a_.)]:= Module[{z},I1[a,0,0,x,y,z]]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.)]:= I1[a,b,0,x,y,z]

soi[dot[x_,y_]^(a_.) dot[z_,w_]^(f_.)]:= I1[a,0,0,0,0,f,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.)]:= 
I1[a,b,c,x,y,z]

soi[dot[x_,w_]^(d_.) dot[y_,z_]^(b_.) dot[z_,w_]^(f_.)]:= 
I1[0,b,0,d,0,f,x,y,z,w]


soi[dot[x_,q_]^(a_.) , q]:= I1q[a,0,x,y,q]

soi[dot[x_,q_]^(a_.) dot[y_,q_]^(b_.) , q]:= I1q[a,b,x,y,q]



soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) dot[x_,
w_]^(d_.)]:= I1[a,b,c,d,0,0,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,w_]^(f_.) dot[x_,
w_]^(d_.)]:= I1[a,b,0,d,0,f,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) dot[x_,
y_]^(d_.) dot[y_,w_]^(e_.)]:= I1[a,b,c,d,e,0,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.)dot[x_,
w_]^(d_.) dot[z_,w_]^(f_.)]:= 
I1[a,b,c,d,0,f,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) dot[y_,
w_]^(e_.) dot[z_,w_]^(f_.)]:= 
I1[a,b,c,0,e,f,x,y,z,w]

soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.)dot[x_,
w_]^(d_.) dot[y_,w_]^(e_.) dot[z_,w_]^(f_.)]:= 
I1[a,b,c,d,e,f,x,y,z,w]


I2[a_,b_,c_,x_,y_,z_]:= 
Module[{i,k,p,r},
If[ TrueQ[EvenQ[b+c]],
1/2 x^(c+a) y^(a+b) z^(b+c) Sum[ Binomial[b,2i] Binomial[i,
p] Binomial[i,k] (2i-1)!! (-1)^(p+k) / ((2i)!! (b+c-2k+
1)) (Sum[ (1/((2r+1)x y)) (-(x^2+y^2)/(2 x y))^(a+b-
(2p+2r+1)),{r,0,Floor[(a+b-2p-1)/2]}] + (-(x^2+y^2)/(2 x y))^(a+b-
2p) (1/(x y)) Log[(x+y)^2/(x-y)^2]/2), {i,0,Floor[b/2]},{p,0,i},
{k,0,i}],0] ]


I22[a_,b_,c_,x_,y_,z_]:= 
Module[{i,k,p,r},
If[ TrueQ[EvenQ[b+c]],
1/2 x^(c+a) y^(a+b) z^(b+c) Sum[ Binomial[b,2i] Binomial[i,
p] Binomial[i,k] (2i-1)!! (-1)^(p+k) / ((2i)!! (b+c-2k+
1)) (Sum[ ((a+b-2p-2r-1) /(2 (2r+1) (x y)^2)) (-(x^2+y^2)/(2 x y))^(a+b-
(2p+2r+2)),{r,0,Floor[(a+b-2p-1)/2]}] + (-(x^2+y^2)/(2 x y))^(a+b-
2p-1) (a+b-2p)/(2 (x y)^2) Log[(x+y)^2/(x-y)^2]/2 + 
(-(x^2+y^2)/(2 x y))^(a+b-2p) 2/(x^2 -y^2)^2), {i,0,Floor[b/2]},
{p,0,i},{k,0,i}],0] ]


I2q[a_,b_,x_,y_,q_]:= 
Module[{i,k,p,r},
2 Pi x^(a-1) y^(b) q^(b+a-1) Sum[ Binomial[b,2k] Binomial[k,
i] Binomial[k,p] (2k-1)!! (-1)^(p+i) /(2k)!! (dot[x,y]
/(x y))^(b-2i) (Sum[ (1/((2r+1))) (-(x^2+q^2)/(2 x q))^(a+b-
(2p+2r+1)),{r,0,Floor[(a+b-2p-1)/2]}] + (-(x^2+q^2)/(2 x q))^(a+b-
2p)  (Log[(x+q)^2/(q-x)^2]/2)), {k,0,Floor[b/2]},{p,0,k},
{i,0,k}] ]


soi[1/(x_^2 + y_^2 +(l_) dot[x_,y_])]:=
I2[0,0,0,x,y,z]

soi[dot[x_,y_]^(a_.) /(x_^2 + y_^2 +(l_) dot[x_,y_])]:=
(2/l)^a I2[a,0,0,x,y,z]

soi[dot[x_,z_]^(c_.) /(x_^2 + y_^2 +(l_) dot[x_,y_])]:=
 I2[0,0,c,x,y,z]



soi[1/(x_^2 + y_^2 +(l_) dot[x_,y_])^2]:=
I22[0,0,0,x,y,z]

soi[dot[x_,y_]^(a_.) /(x_^2 + y_^2 +(l_) dot[x_,y_])^2]:=
(2/l)^a I22[a,0,0,x,y,z]

soi[dot[x_,z_]^(c_.) /(x_^2 + y_^2 +(l_) dot[x_,y_])^2]:=
 I22[0,0,c,x,y,z]


soi[1/(x_^2 + q_^2 +(l_) dot[x_,q_]) , q]:=
I2q[0,0,x,y,q]

soi[dot[x_,q_]^(a_.) /(x_^2 + q_^2 +(l_) dot[x_,q_]), q]:=
(2/l)^a I2q[a,0,l x/2,y,q]

soi[dot[y_,q_]^(c_.) /(x_^2 + q_^2 +(l_) dot[x_,q_]), q]:=
 I2q[0,c,l x/2,y,q]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.)/(x_^2 + y_^2 +(l_) dot[x_,
y_])]:=(2/l)^a I2[a,b,0,x,y,z]

soi[dot[x_,z_]^(c_.) dot[y_,z_]^(b_.)/(x_^2 + y_^2 +(l_) dot[x_,
y_])]:=(2/l)^c I2[0,b,c,x,y,z]



soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.)/(x_^2 + y_^2 +(l_) dot[x_,
y_])^2]:=(2/l)^a I22[a,b,0,x,y,z]

soi[dot[x_,z_]^(c_.) dot[y_,z_]^(b_.)/(x_^2 + y_^2 +(l_) dot[x_,
y_])^2]:=(2/l)^c I22[0,b,c,x,y,z]



soi[dot[x_,q_]^(a_.) dot[y_,q_]^(b_.)/(x_^2 + q_^2 +(l_) dot[x_,
q_]), q]:=(2/l)^a I2q[a,b,l x/2,y,q]



soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) /(x_^2 + 
y_^2 +(l_) dot[x_,y_])]:=(2/l)^(a+c) I2[a,b,c,x,y,z]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) /(x_^2 + 
y_^2 +(l_) dot[x_,y_])^2]:=(2/l)^(a+c) I22[a,b,c,x,y,z]


I3[a_,b_,c_,x_,y_,z_]:= 
Module[{r,s,i,p,k},
1/4 x^(c+a) y^(a+b) z^(b+c) Sum[ Binomial[b,2i] Binomial[i,
p] Binomial[i,k] (2i-1)!! (-1)^(p+k) /(2i)!! (Sum[ 
(1/((2r+1)x z)) (-(x^2+z^2)/(2 x z))^(a+b-
(2p+2r+1)),{r,0,Floor[(a+b-2p-1)/2]}] + (-(x^2+z^2)/(2 x z))^(a+b-
2p) (1/(x z)) Log[(x+z)^2/(x-z)^2]/2)         (Sum[ 
(-1/((2s+1)x y)) ((x^2+y^2)/(2 x y))^(a+b-
(2k+2s+1)),{s,0,Floor[(a+b-2k-1)/2]}] + ((x^2+y^2)/(2 x y))^(a+b-
2k) (1/(x y)) Log[(x+y)^2/(x-y)^2]/2), 
{i,0,Floor[b/2]},{p,0,i},{k,0,i}]  ]


I3[a_,b_,x_,y_,q_]:= 
Module[{r,i},
(-1/2)^(a+b) (x^2 + q^2)^a (y^2 + q^2)^b 4 Pi W[x,y,q] +
(x^2 + q^2)^a 2^(-a-b)  Sum[ Binomial[b,r+1] (-1)^(a+b-1-r) (y^2 + 
q^2)^(b-r-1)  saint[ Expand[ dot[q+y,q+y]^r /dot[q+x,q+x] 
//. dist] ,q],{r,0,b-1}] + (y^2 + q^2)^b 2^(-a-b)  Sum[ 
Binomial[a,i+1] (-1)^(a+b-1-i) (x^2 + 
q^2)^(a-i-1)  saint[ Expand[ dot[q+x,q+x]^i /dot[q+y,q+y] 
//. dist] ,q],{i,0,a-1}] + Sum[ Binomial[b,r+1] Binomial[a,
i+1] (-1)^(a+b-i-r) (x^2 + q^2)^(a-1-i) (y^2 + q^2)^(b-1-
r) 2^(-a-b) saint[ Expand[ dot[q+x,q+x]^i dot[q+y,q+y]^r 
//. dist] ,q],{i,0,a-1},{r,0,b-1}] ]


soi[ 1/((x_^2 + 
y_^2 +(l_) dot[x_,y_])(x_^2 + z_^2 +(m_) dot[x_,z_]) )]:=
I3[0,0,0,x,y,z]


soi[ 1/((q_^2 + 
y_^2 +(l_) dot[q_,y_])(q_^2 + z_^2 +(m_) dot[q_,z_]) ),q_]:=
I3[0,0,m z/2,l y/2,q]


soi[ dot[y_,z_]^(b_.) /((x_^2 + 
y_^2 +(l_) dot[x_,y_])(x_^2 + z_^2 +(m_) dot[x_,z_]) )]:=
(-4/(m l))^b I3[0,b,0,x,y,z]


soi[dot[x_,y_]^(a_.)   /((x_^2 + 
y_^2 +(l_) dot[x_,y_])(x_^2 + z_^2 +(m_) dot[x_,z_]) )]:=
(-2/l)^a I3[a,0,0,x,y,z]


soi[ dot[q_,y_]^(a_.)/((q_^2 + y_^2 +
(l_) dot[q_,y_])(q_^2 + z_^2 +(m_) dot[q_,z_]) ),q_]:=
(2/l)^a I3[a,0,l y/2,m z/2,q]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.)/((x_^2+y_^2+(l_) dot[x_,y_])(x_^2+z_^2+(m_) dot[x_,z_]))]:=(-2/l)^(a+b) (2/m)^b I3[a,b,0,x,y,z]


soi[dot[x_,y_]^(a_.) dot[z_,x_]^(c_.)/((x_^2+y_^2+(l_) dot[x_,y_])(x_^2+z_^2+(m_) dot[x_,z_]))]:=(-2/l)^a (2/m)^c I3[a,0,c,x,y,z]


soi[dot[q_,y_]^(a_.) dot[q_,z_]^(b_.)/((q_^2+y_^2+(l_) dot[q_,y_])(q_^2+z_^2+(m_) dot[q_,z_])),q_]:=(2/l)^a (2/m)^b I3[a,b,l y/2,m z/2,q]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) /((x_^2 + 
y_^2 +(l_) dot[x_,y_])(x_^2 + z_^2 +(m_) dot[x_,z_]) )]:=
(-2/l)^(a+b) (2/m)^(b+c) I3[a,b,c,x,y,z]


I4[a_,b_,c_,x_,y_,z_]:=  
Module[{i,k,t,u,v,r,s,w,h},
						1/4 x^(c+a) y^(a+b) z^(b+c) Sum[
((2k-1)!! /(2k)!! ) Binomial[b,i] Binomial[c,2k-i] Binomial[k,
r] (-1)^(r+v+i) Binomial[c-2k+i,t] Binomial[b-i,u] Binomial[k,
v]  x^(2i-2k+u+c-t) y^(2k-2i+b+t-u) ( Sum[1/(2 s+1) (-1/
(2 z))^(b+c-2k+2r-2s-1) Binomial[b+c-2k+2r-2s-1,w] z^(2w-
1) inti[a+t+u+2v,k+s+w+1-r,x, y], {s,0,Floor[(b+
c-2k+2r-1)/2]}, {w,0,b+c-2k+2r-2s-1}] + 
(-1/(2 z))^(b+c-2k+2r) Sum[ 
Binomial[2r-2k+b+c,w] z^(2w-1) (2/ (2 x y)^(a+t+u+
2v+1) ) Binomial[a+t+u+2v,h] (- (x^2 + y^2))^(a+t+u+2v-
h) deltaj[h-k+r-w,x,y,z], {w,0,2r-2k+b+c},{h,0,a+t+u+2v}] ), 
{i,0,b},{k,Floor[(i+1)/2],Floor[(i+c)/2]},{r,0,k},{t,0,c-2k+i},
{u,0,b-i},{v,0,k}]
]


the[n_]:= If[n>=0,1,0]

inti[n_,m_,x_,y_]:= Module[{k,p,i},
Sum[Binomial[n-2k-1,m-1] Binomial[n-2k-m,
p] (-1)^(n+m) the[n-2k-m] x^(2p+2k-n) y^(n-2k-2p-2m) /(2^(n-2k-
1) (2k+1)), {k,0,Floor[(n-1)/2]},{p,0,n-2k-m}] - Sum[ Binomial[
n,m-1] Binomial[n-m+1,p] (-1)^(n+m) /2^n the[n-m+1] x^(2p-n-
1) y^(n-2m-2p+1) Log[(x+y)^2/(x-y)^2]/2, {p,0,n-m+1}] -
Sum[ Binomial[n,m-1-p] Binomial[p,2k+1] Binomial[n-m+2p-2k,
i] (-1)^(p+n+m) 2^(2k+1-n) /(p (x^2-y^2)^(2p) ) the[n-m+1+
p] x^(2k+2i-n) y^(n+4p-2i-2k-2m), {p,1,m-1},{k,0,Floor[
(p-1)/2]}, {i,0,n-m+2p-2k}]
] /; TrueQ[n>=0]


deltaj[0,x_,y_,z_]:=  (x+y) Log[(x+y+z)^2/(x+y-z)^2]/2 - 
Abs[x-y] Log[Abs[(Abs[x-y]+z)/(Abs[x-y]-z)]] + z Log[Abs[
((x+y)^2 -z^2)/((x-y)^2 -z^2)]] 

deltaj[n_?Positive,x_,y_,z_]:= Module[{i,p,k},
Sum[Binomial[2n,p] Binomial[p+1,2k] Binomial[2k,2i+1] (4 (-1)^(p+
1) /(p+1)^2 ) x^(2k-2i-1) y^(2i+1) z^(2n-2k+1) ,{p,0,2n},
{k,0,Floor[(p+1)/2]},{i,0,k-1}] + (x+y)^(2n+1) Log[Abs[
(x+y+z)/(x+y-z)]] /(2n+1)- Abs[x-y]^(2n+1) Log[Abs[
(Abs[x-y]+z)/(Abs[x-y]-z)]] /(2n+1) + z^(2n+1) Log[Abs[
((x+y)^2 -z^2)/((x-y)^2 -z^2)]] /(2n+1)
]

deltaj[n_?Negative,x_,y_,z_]:=  Module[{p,k},
Sum[2/(-2n-1)  Binomial[2k,2p+1] x^(2p+1)  y^(2k-2p
-1) z^(2k+2n+1) /(k (x^2-y^2)^(2k)) ,{k,1,-n-1},{p,0,k-1}] +
 1/(-2n-1) Abs[x-y]^(2n+1) Log[Abs[(Abs[x-y]+z)/(Abs[
 x-y]-z)]] - 1/(-2n-1) (x+y)^(2n+1) Log[Abs[(x+y+
 z)/(x+y-z)]] - 1/(-2n-1) z^(2n+1) Log[Abs[
((x+y)^2 -z^2)/((x-y)^2 -z^2)]] + 2/(-2n-1) z^(2n+
1) Log[Abs[(x+y)/(x-y)]] 
]


soi[ 1/( (x_^2 + y_^2 + z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + 
(m_) dot[y_,z_])  )]:= I4[0,0,0,x,y,z]


soi[ dot[x_,y_]^(a_.) /( (x_^2 + y_^2 + z_^2 +2 ((n_.)dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^a I4[a,0,0,x,y,z]


soi[ dot[y_,z_]^(b_.) /( (x_^2 + y_^2 + z_^2 +2 ((n_.)dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I4[0,b,0,x,y,z]


soi[ dot[x_,z_]^(c_.) /( (x_^2 + y_^2 + z_^2 +2 ((n_.)dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= I4[0,0,c,x,y,z]


soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) /( (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^(a+b) I4[a,b,0,x,y,z]


soi[ dot[y_,z_]^(b_.)  dot[x_,z_]^(c_.) /( (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^b I4[0,b,c,x,y,z]


soi[  dot[x_,z_]^(c_.) dot[x_,y_]^(a_.)/( (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^a I4[a,0,c,x,y,z]


soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /( (x_^2 +
y_^2 + z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + 
(m_) dot[y_,z_])  )]:= (n)^(a+b) I4[a,b,c,x,y,z]


I5[a_,b_,c_,x_,y_,z_]:= 
Module[{i,k,t,u,v,r,s,w,h},
						1/4 x^(c+a) y^(a+b) z^(b+c) Sum[
((2k-1)!! /(2k)!! ) Binomial[b,i] Binomial[c,2k-i] Binomial[k,
r] (-1)^(r+v+i) Binomial[c-2k+i,t] Binomial[b-i,u] Binomial[k,
v]  x^(2i-2k+u+c-t) y^(2k-2i+b+t-u) ( Sum[1/(2 s+1) (-1/
(2 z))^(b+c-2k+2r-2s-1) Binomial[b+c-2k+2r-2s-1,w] z^(2w-
1) inti[a+t+u+2v,k+s+w+2-r,x, y], {s,0,Floor[(b+
c-2k+2r-1)/2]}, {w,0,b+c-2k+2r-2s-1}] + 
(-1/(2 z))^(b+c-2k+2r) Sum[ 
Binomial[2r-2k+b+c,w] z^(2w-1) (2/ (2 x y)^(a+t+u+
2v+1) ) Binomial[a+t+u+2v,h] (- (x^2 + y^2))^(a+t+u+2v-h) deltaj[
h-k+r-w-1,x,y,z] , {w,0,2r-2k+b+c},{h,0,a+t+u+2v}] ), {i,0,b},{k,
Floor[(i+1)/2],Floor[(i+c)/2]},{r,0,k},{t,0,c-2k+i},{u,0,b-i},
{v,0,k}]
]


soi[ 1/( (x_^2 + y_^2 + (m_) dot[x_,y_]) (x_^2 + y_^2 + 
z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
I5[0,0,0,x,y,z]


soi[ 1/( (y_^2 + z_^2 + (m_) dot[y_,z_]) (x_^2 + y_^2 + 
z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
I5[0,0,0,y,z,x]


soi[ 1/( (x_^2 + z_^2 + 2 dot[x_,z_]) (x_^2 + y_^2 + 
z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
I5[0,0,0,z,x,y]


soi[ dot[x_,y_]^(a_.) /((x_^2 + y_^2 + (m_) dot[x_,y_]) (x_^2 + 
y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^a I5[a,0,0,x,y,z]
 
 soi[ dot[x_,y_]^(a_.) /((y_^2 + z_^2 + (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:=  (n)^a I5[0,0,a,y,z,x]
 
 soi[ dot[x_,y_]^(a_.) /((x_^2 + z_^2 + 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:=  (n)^a I5[0,a,0,z,x,y]
 
 


soi[ dot[y_,z_]^(b_.) /((x_^2 + y_^2 + (m_) dot[x_,y_]) (x_^2 + 
y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I5[0,b,0,x,y,z]
 
 soi[ dot[y_,z_]^(b_.) /((y_^2 + z_^2 + (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I5[b,0,0,y,z,x]
 
 soi[ dot[y_,z_]^(b_.) /((x_^2 + z_^2 + 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I5[0,0,b,z,x,y]


soi[ dot[x_,z_]^(c_.) /((x_^2 + y_^2 + (m_) dot[x_,y_]) (x_^2 + 
y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= I5[0,0,c,x,y,z]
 
 soi[ dot[x_,z_]^(c_.) /((y_^2 + z_^2 + (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:=  I5[0,c,0,y,z,x]
 
 soi[ dot[x_,z_]^(c_.) /((x_^2 + z_^2 + 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= I5[c,0,0,z,x,y]


soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) /((x_^2 + y_^2 + 
(m_) dot[x_,y_]) (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^(a+b) I5[a,b,0,x,y,z]
 
 soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) /((y_^2 + z_^2 + 
 (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^(a+b) I5[b,0,a,y,z,x]
 
 soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) /((x_^2 + z_^2 + 
 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^(a+b) I5[0,a,b,z,x,y]


soi[ dot[y_,z_]^(b_.)  dot[x_,z_]^(c_.) /((x_^2 + y_^2 + 
(m_) dot[x_,y_]) (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^b I5[0,b,c,x,y,z]

 soi[ dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /((y_^2 + z_^2 + 
 (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I5[b,c,0,y,z,x]
 
 soi[ dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /((x_^2 + z_^2 + 
 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^b I5[c,0,b,z,x,y]


soi[  dot[x_,z_]^(c_.) dot[x_,y_]^(a_.) /( (x_^2 + y_^2 + 
(m_) dot[x_,y_]) (x_^2 + y_^2 + z_^2 +
2 ((n_.) dot[x_,y_] + dot[x_,z_]) + (m_) dot[y_,z_])  )]:= 
(n)^a I5[a,0,c,x,y,z]
 
 soi[  dot[x_,z_]^(c_.) dot[x_,y_]^(a_.) /((y_^2 + z_^2 + 
 (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^a I5[0,c,a,y,z,x]
 
 soi[ dot[x_,z_]^(c_.) dot[x_,y_]^(a_.) /((x_^2 + z_^2 + 
 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^a I5[c,a,0,z,x,y]


soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /((x_^2 +
 y_^2 + (m_) dot[x_,y_]) (x_^2 +
y_^2 + z_^2 +2 ((n_.) dot[x_,y_] + dot[x_,z_]) + 
(m_) dot[y_,z_])  )]:= (n)^(a+b) I5[a,b,c,x,y,z]

soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /((y_^2 + 
z_^2 + (m_) dot[y_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^(a+b) I5[b,c,a,y,z,x]
 
 soi[ dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[x_,z_]^(c_.) /((x_^2 + 
 z_^2 + 2 dot[x_,z_]) (x_^2 + 
 y_^2 + z_^2 +2 ((n_.) dot[x_,y_] +
 dot[x_,z_]) + (m_) dot[y_,z_])  )]:= (n)^(a+b) I5[c,a,b,z,x,y]


I6[a_,b_,c_,x_,y_,z_,d_]:= 
Module[{i,k,p}, If[ TrueQ[EvenQ[b+c]], 1/2 x^(c+a) y^(a+
b) z^(b+c) Sum[ Binomial[b,
2i] Binomial[i,p] Binomial[i,k] (2i-1)!! (-1)^(p+k) / ((2i)!! (b+
c-2k+1)) K[d,a+b-2p,x,y], {i,0,Floor[b/2]},{p,0,i},{k,0,i}],0] ] /;
TrueQ[d>-1]


K[-1/2,m_,x_,y_]:=  Module[{i}, Sum[ Binomial[m,i] (-1)^(m-
i) (x^2 + y^2)^(m-i) ( (x+y)^(2i+3) - (Max[x,y]-Min[x,y])^(2i+
3) )/((2i+3) 2^m x^(m+1) y^(m+1) ),{i,0,m}]]


K[0,m_,x_,y_]:= (1 + (-1)^m)/(m+1)


K[1/2,m_,x_,y_]:= Module[{i,p,k}, Sum[ Binomial[m,k] (-1)^k Binomial[
k,p] Binomial[2m-2k,2i] (Max[x,y]/Min[x,y])^(m-2i-2p) /((i+
1/2) 2^m Max[x,y]),{k,0,m},{p,0,k},{i,0,m-k}]]


K[1,m_,x_,y_]:= Module[{k}, Sum[(-1)^(m+1) ((x^2 + y^2)/(2 x y))^(m-
2k-1) /((2k+1) x y),{k,0,Floor[(m-1)/2]}]] + (-1)^(m) ((x^2 + 
y^2)/(2 x y))^(m) Log[Abs[(x+y)/(x-y)]]/(x y)


K[3/2,m_,x_,y_]:= Module[{i,p,k}, Sum[ Binomial[m-1,k] (-1)^k Binomial[
k,p] Binomial[2m-2k-2,2i-2] m (Max[x,y]/Min[x,y])^(m-2i-2p) /((i-
1/2) 2^(m-1) Max[x,y] Min[x,y]^2),{k,0,m-1},{p,0,k},{i,1,m-k}]] +
Module[{i,p,k}, Sum[ Binomial[m,k] (-1)^(k+1) Binomial[k,
p] Binomial[2m-2k-1,2i-1] (Max[x,y]/Min[x,y])^(m-2i-2p) /(2^(m-
1) Max[x,y] Min[x,y]^2),{k,0,m-1},{p,0,k},{i,1,m-k}]] +
(-1/2)^m Module[{p},Sum[Binomial[m,p] x^(m-2p-1) y^(2p-m
-1) (Abs[x-y]^(-1) - (x+y)^(-1) ), {p,0,m}]]


Kold[2,m_,x_,y_]:= Module[{k}, Sum[(-1)^(m) (m-2k-1) ((x^2 + 
y^2)/(2 x y))^(m-2k-2) /((2k+1) 2 x^2 y^2),{k,0,Floor[(m-1)/2]}]] + 
(-1)^(m) ((x^2 + y^2)/(2 x y))^(m) 1/8 ( (1/x +1/y)/(x-y) + 
(1/x -1/y)/(x+y) )^(2) + 
m (-1)^(m-1) ((x^2 + y^2)/(2 x y))^(m-1) Log[Abs[(x+y)/(x-
y)]]/(2 x^2 y^2)


K[2,m_,x_,y_]:= Module[{k}, Sum[(-1)^(m) (m-2k-1) ((x^2 + 
y^2)/(2 x y))^(m-2k-2) /((2k+1) 2 x^2 y^2),{k,0,Floor[(m-1)/2]}]] + 
(-1)^(m) ((x^2 + y^2)/(2 x y))^(m) 2/(x^2-y^2)^2 + 
m (-1)^(m-1) ((x^2 + y^2)/(2 x y))^(m-1) Log[Abs[(x+y)/(x-
y)]]/(2 x^2 y^2)


K[5/2,m_,x_,y_]:= Module[{i,p,k}, Sum[ Binomial[m-2,k] (-1)^k Binomial[
k,p] Binomial[2m-2k-4,2i-2] m(m-1) (Max[x,y]/Min[x,y])^(m-2i-2p) 4/((i-
1/2) 3 2^m Max[x,y]^3 Min[x,y]^2),{k,0,m-2},{p,0,k},{i,1,m-k-1}]] +
Module[{i,p,k}, Sum[(-8/3) Binomial[m-1,k] (-1)^k Binomial[
k,p] Binomial[2m-2k-3,2i-1] m (Max[x,y]/Min[x,y])^(m-2i-2p) /(2^m Max[
x,y]^3 Min[x,y]^2),{k,0,m-2},{p,0,k},{i,1,m-k-
1}]] + (8/3) m (-1)^m 2^(-m-1) Module[{p}, Sum[ Binomial[m-1,
p] x^(m-2p-3) y^(2p-m-1) ( 1/(x+y) - 1/Abs[x-y] ), {p,0,m-1}]] +
Module[{i,p,k}, Sum[ Binomial[m,k] (-1)^(k) (m-k-1/2) Binomial[k,
p] Binomial[2m-2k-3,2i-1]  (Max[x,y]/Min[x,y])^(m-2i-2p) 4/(2^(m
) 3 Max[x,y]^3 Min[x,y]^2),{k,0,m-2},{p,0,k},{i,1,m-k-1}]] +
(4/3) Module[{p,k},Sum[Binomial[m,k] (-1)^k (m-k-1/2) Binomial[k,
p] x^(2k-2p-m-1) y^(2p-m-1) (-Abs[x-y]^(2m-2k-3) + (x+y)^(2m-2k-
3) )/(2^(m+1)), {k,m-1,m},{p,0,k}]]


Kold[3,m_,x_,y_]:= Module[{k}, Sum[(-1)^(m+1) (m-2k-1) (m-2k-2) ((x^2 + 
y^2)/(2 x y))^(m-2k-3) /((2k+1) 8 x^3 y^3),{k,0,Floor[(m-1)/2]}]] + 
m (-1)^(m-1) ((x^2 + y^2)/(2 x y))^(m-1) ( (1/x +1/y)/(x-y) + 
(1/x -1/y)/(x+y) )^(2) 1/(x y 16) + 
(-1)^(m) ((x^2 + y^2)/(2 x y))^(m) 2(x^2 +y^2) ( (1/x +1/y)/(x-y) + 
(1/x -1/y)/(x+y) )^(4) /(4^4) + 
m (m-1) (-1)^(m) ((x^2 + y^2)/(2 x y))^(m-2) Log[Abs[(x+y)/(x-
y)]]/(8 x^3 y^3)


K[3,m_,x_,y_]:= Module[{k}, Sum[(-1)^(m+1) (m-2k-1) (m-2k-2) ((x^2 + 
y^2)/(2 x y))^(m-2k-3) /((2k+1) 8 x^3 y^3),{k,0,Floor[(m-1)/2]}]] + 
m (-1)^(m-1) ((x^2 + y^2)/(2 x y))^(m-1) /(x y (x^2-y^2)^2) + 
(-1)^(m) ((x^2 + y^2)/(2 x y))^(m) 2(x^2 +y^2)/((x^2-y^2)^4) + 
m (m-1) (-1)^(m) ((x^2 + y^2)/(2 x y))^(m-2) Log[Abs[(x+y)/(x-
y)]]/(8 x^3 y^3)


soi[(x_^2 + y_^2 +(l_) dot[x_,y_])^(d_.)]:=
I6[0,0,0,x,y,z,-d]

soi[dot[x_,y_]^(a_.) (x_^2 + y_^2 +(l_) dot[x_,y_])^(d_.)]:=
(2/l)^a I6[a,0,0,x,y,z,-d]

soi[dot[x_,z_]^(c_.) (x_^2 + y_^2 +(l_) dot[x_,y_])^(d_.)]:=
(2/l)^c I6[0,0,c,x,y,z,-d]

soi[dot[y_,z_]^(c_.) (x_^2 + y_^2 +(l_) dot[x_,y_])^(d_.)]:=
(2/l)^c I6[0,0,c,x,y,z,-d]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) (x_^2 + y_^2 +(l_) dot[x_,
y_])^(d_.)]:=(2/l)^a I6[a,b,0,x,y,z,-d]

soi[dot[z_,x_]^(c_.) dot[y_,z_]^(b_.) (x_^2 + y_^2 +(l_) dot[x_,
y_])^(d_.)]:=(2/l)^c I6[0,b,c,x,y,z,-d]


soi[dot[x_,y_]^(a_.) dot[y_,z_]^(b_.) dot[z_,x_]^(c_.) (x_^2 + 
y_^2 +(l_) dot[x_,y_])^(d_.)]:=(2/l)^(a+c) I6[a,b,c,x,y,z,-d]


Protect[soi,I1,I1q,I2,I22,I2q,I3,the,inti,saint,dist]


Share[];
